### ISSUE TITLE
动态壁纸好像不支持fly格式，能说明一下支持的具体有哪些格式吗？

### ISSUE THREAD

**Issue by rs-v** [zhaotianff/Master-Zhao#1]

**Comment by zhaotianff** [comment]
你好，动态壁纸这里用了WPF的MediaElement控件，一般的MP4,AVI,MPEG等格式都是支持的。
详细的格式支持可以参考这个链接
https://docs.microsoft.com/zh-cn/previous-versions/windows/silverlight/dotnet-windows-silverlight/cc189080(v=vs.95)?redirectedfrom=MSDN。
